/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jeffrey;

import jeffrey.faults.MemoryFault;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test
    public void testMemory() throws InterruptedException {
        MemoryFault mf= new MemoryFault();
        mf.apply();
    }
}
